version: '3.8'

services:
  rapid-minutes-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rapid-minutes-dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - MAX_FILE_SIZE=10485760
      - MAX_CONCURRENT_PROCESSES=2
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000,http://127.0.0.1:8000
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    restart: unless-stopped
    networks:
      - rapid-minutes-dev-network

  redis-dev:
    image: redis:7-alpine
    container_name: rapid-minutes-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    restart: unless-stopped
    networks:
      - rapid-minutes-dev-network

networks:
  rapid-minutes-dev-network:
    driver: bridge

volumes:
  redis-dev-data: