version: '3.8'

services:
  rapid-minutes:
    build: .
    container_name: rapid-minutes-export
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MAX_FILE_SIZE=10485760  # 10MB
      - MAX_CONCURRENT_PROCESSES=3
      - UPLOAD_TIMEOUT=60
      - PROCESSING_TIMEOUT=300
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rapid-minutes-network

  nginx:
    image: nginx:alpine
    container_name: rapid-minutes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rapid-minutes
    restart: unless-stopped
    networks:
      - rapid-minutes-network

networks:
  rapid-minutes-network:
    driver: bridge

volumes:
  uploads-data:
  logs-data: